### ISSUE TITLE
setDefault() ambiguous reference to overloaded definition

### ISSUE THREAD

**Issue by xanderdunn** [tatsuhiro-t/argparse4j#47]
On any argument I add to my parser with a default value, I'm told that it's ambiguous which overloaded method it's referring to:
```bash
/local/dev/odin-core/master/src/main/scala/ai/osaro/master/Main.scala:75: ambiguous reference to overloaded definition,
both method setDefault in trait Argument of type [E](x$1: E*)net.sourceforge.argparse4j.inf.Argument
and  method setDefault in trait Argument of type (x$1: Any)net.sourceforge.argparse4j.inf.Argument
match argument types (String)
    parser.addArgument("-greed").setDefault("0.9").help("Specify hash function to use")
```

Note that I'm in Scala 2.11.7.  Does argparse4j not work with Scala out of the box?

**Comment by tatsuhiro-t** [comment]
It seems scala complaints ambiguity among the following methods of Argument interface:
```java
Argument setDefault(Object value);
<E> Argument setDefault(E... values);
```
Interestingly, Java compiler happily compiles the program when I use setDefault("foo") or something.
I have not used scala before, but since scala and java are different language after all, so it is not surprising scala failed to compile this.

Perhaps, https://github.com/mdekstrand/argparse4s may help your situation?

**Comment by xanderdunn** [comment]
@tatsuhiro-t Thanks for looking at this.  This is the first instance of a Java library I've run into that isn't compatible with Scala, as they are [interoperable](http://www.scala-lang.org/old/faq/4.html).  However, I suppose it isn't surprising that certain oddities aren't compatible.

**Comment by tatsuhiro-t** [comment]
This is a well known interop problem between scala and java.  There are many stackoverflow questions about this.  For example, see http://stackoverflow.com/questions/3313929/how-do-i-disambiguate-in-scala-between-methods-with-vararg-and-without

**Comment by xanderdunn** [comment]
@tatsuhiro-t Thanks!  This is good to know!
