### ISSUE TITLE
Set choices by default if type is Boolean

### ISSUE THREAD

**Issue by asieira** [tatsuhiro-t/argparse4j#51]
If we configure an argument with `.type(Boolean.class)` and no value was previously set for `choices`, I would like to suggest that it be set by default to the equivalent of `.choices(Boolean.TRUE, Boolean.FALSE)`.

This will make the default help message much more user-friendly.

**Comment by tatsuhiro-t** [comment]
Current behaviour is everything that case-insensitive-matches "true" is evaluated to true value.
Because of this, I personally would like to avoid to set choices implicitly.
That said, I like the idea to improve the help message for boolean types.

BTW, [storeTrue/storeFalse](http://argparse4j.sourceforge.net/usage.html#arguments-storetrue-and-arguments-storefalse) do not take any argument, and acts like boolean arguments, but split into 2 flags (if you want to enable/disable independently).  They don't have this kind of issue since they do not take an argument.

**Comment by asieira** [comment]
My main point here would be to improve the help message, so I guess we agree on that. No need to change the way the values are interpreted IMHO.

**Comment by tatsuhiro-t** [comment]
My first cut for this issue is #52.
Could you test it please?

**Comment by asieira** [comment]
I have tested it and it works perfectly!

**Comment by tatsuhiro-t** [comment]
Thank you!  #52 was merged now.
