### ISSUE TITLE
java.nio.file.path PathArgumentType implementation

### ISSUE THREAD

**Issue by kpathak13** [tatsuhiro-t/argparse4j#58]
Since `Path` is being accepted as a new java standard, it would make sense to have a new implementation for `PathArgumentType`.

**Comment by kpathak13** [comment]
I would like to contribute if this is approved.

**Comment by tatsuhiro-t** [comment]
Thank you.  To include Path in our API, we have to set compiler settings to Java8 standard.
argparse4j is still compiled with Java5 standard (maven default).  Since Java7 has already been in EOL, I'm wondering we should upgrade change the compiler settings.  But I'm not sure which java version is the best way for this kind of small utility project.

**Comment by kpathak13** [comment]
What is the hesitation to compile it with `Java 8`? I am one of those who has already accepted `Java 8` as the standard. :smiley:

**Comment by tatsuhiro-t** [comment]
My bad, Path was introduced since Java7 not Java8.

I'm wondering how the applications using argparse4j break when we upgrade target compiler version to Java7.  It looks like that they don't break if Java runtime is at least Java7, even though they use target compiler is still older than Java7, linking argparse4j which itself targeted to Java7.  Is that correct?

**Comment by kpathak13** [comment]
@tatsuhiro-t Generally speaking, what you said is correct. Here is the [Compatibility](http://www.oracle.com/technetwork/java/javase/compatibility-417013.html) guidelines from Oracle.

**Comment by tatsuhiro-t** [comment]
All right, we decided to go with 1.8 now.  Contribution is always welcome.

**Comment by kpathak13** [comment]
Thanks. I will be creating pull request.

**Comment by jstuyts** [comment]
As the move to Java 8 has been postponed (https://github.com/tatsuhiro-t/argparse4j/issues/63), I think this issue and https://github.com/tatsuhiro-t/argparse4j/issues/59 need to be implemented in extension projects, so argparse4j does not depend on Java 7 or Hadoop. But this would require changes to the directory structure. This is just a suggestion:

    parent
    +-- extensions
    |   +-- hadoop
    |   +-- java7
    \-- argparse4j

**Comment by jstuyts** [comment]
Closing as this has been fixed by #87. If more Java 7 argument types are needed, please open a new issue.
